### PR TITLE
Add source addr

### PR DESCRIPTION
**Pull request by pepoluan**
My changes allow the setting of Source IP Address for `ping.py` (and `ping` module)

This is roughly equivalent to the `-I` option of `ping` program.

In addition, I've added two files to ease further development/testing:

- `.hgignore` to assist Mercurial development using PyCharm
- `__init__.py` to allow `import` for testing, in accordance to module guidelines

### CODE REVIEW

**Comment by EclectickMedia** [comment]
I see no reason for an internal .hgignore/.gitignore to be made public.

People can add their own .hgignore/.gitignore to their own repositories.

It really just presents more clutter to the repository, and is not something that everyone uses. (I for example write all my code in Vim with purely git integration)


Also, is removing pre existing code because your code linter complains really good motivation for doing so?

**Comment by EclectickMedia** [comment]
I also have no issues importing the repo without the `__init__.py` file.

I mean, its a good thing to have and ensures code handles the repo as a package, but should it be added or just implied?

**Comment by EclectickMedia** [comment]
Question pertaining to this comment:
> ... dropped the index [0] ...

Can you cite affected code?

**Comment by pepoluan** [comment]
> I see no reason for an internal .hgignore/.gitignore to be made public.
>
> People can add their own .hgignore/.gitignore to their own repositories.

Okay, I see your point. I'll drop the *ignore files and recommit later today. (I have to go somewhere right now).

> I also have no issues importing the repo without the __init__.py file.
>
> I mean, its a good thing to have and ensures code handles the repo as a package, but should it be added or just implied?

Python3 actually requires packages to have `__init__.py` in their basedir if the package is not installed into the lib directory (using `pip` or the likes), but is instead (for example) git-cloned to a subdirectory.

Refer to [the Python3 docs](https://docs.python.org/3/tutorial/modules.html#packages): _The `__init__.py` files are required to make Python treat the directories as containing packages_

An empty `__init__.py` is enough to satisfy this requirement.

> Question pertaining to this comment:
>
> > ... dropped the index [0] ...
>
> Can you cite affected code?

Ohh... github 'extracted' the inline comments, I see... *sighs*

It's line 424|428 in the commit for `ping.py`

It originally ended in:

```
verbose=False)[0]
```

Now it ends in:

```
verbose=False, sourceIP=sourceIP)
```

**Comment by EclectickMedia** [comment]
> Python3 actually requires packages to have __init__.py

I work exclusively in 3.5 or higher, and can't replicate any issues as the code stands. I mean, generally it works fine and isn't an issue. Just pointing out that I don't need it. *(see [my own repo][1] for use case that works without the `__init__.py`)* It should likely be added anyways, just for consistency' sake.

> It's line 424|428

I see the reference removed now. While the `[0]` call isn't necessary as `quiet_ping` doesn't need to be specific with the results, I would believe it should be kept just for consistency across the code. Keep in mind that the `[0]/[1]` access is only a bandaid fix to some information, *nominally TTL info*, that was being dropped previously. See #20 and #22 (accompanying pull request) for the original discussion on this feature.

> Ohh... github 'extracted' the inline comments, I see... sighs

Dontcha just love when GitHub does things the command line utility doesn't?

**Comment by pepoluan** [comment]
Sorry for the delay! I've removed the .ignore files.

**Comment by EclectickMedia** [comment]
Great work by the way!

No worries about the delay.

I normally have to wait upwards of a month for the repo owner to reply to issues.

**Pull request merged**
